baseURL = "https://joel-becker.com/"
languageCode = "en-us"
title = "Joel Becker"

[permalinks]
personal = "/personal/:filename/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
