baseurl = "https://joel-becker.github.io/"
title = "Joel Becker"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Joel Becker"
    info = "Predoctoral Fellow, Harvard University and NBER"
    description = "Joel Becker's website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"
    footercontent = "Enter a text here."

    dateformat = "January 2, 2006"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    hidecredits = true
    hidecopyright = true

    rtl = false
    math = true

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/joel-becker/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/joel_bkr/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/joel-becker/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Research"
    weight = 2
    url = "/research/"
[[menu.main]]
    name = "CV"
    weight = 3
    url = "/cv/"
[[menu.main]]
    name = "Contact me"
    weight = 4
    url = "/contact/"
